---
ID: "6f2ead4b-d9da-4303-b6da-ffb037122db8"
Parent: "33eed0f3-26bd-4ddb-9c34-95a725c84fee"
Template: "33eed0f3-26bd-4ddb-9c34-95a725c84fee"
Path: /sitecore/templates/Foundation/Storefront/LanguageFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{1A6F92E8-FEBC-4E02-BB22-7A848F48EAD4}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230106T143718Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f64c190c-23d3-4cbc-b05b-eb7cba104b6e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230106T143733Z
