---
ID: "4ada624b-52ed-4919-b4c9-94a9d0e6f5e9"
Parent: "dc74250c-a4ca-402e-8aa0-fbd5d10a874b"
Template: "dc74250c-a4ca-402e-8aa0-fbd5d10a874b"
Path: /sitecore/templates/System/Email/Common Template/Parameter Templates/Body Text/__Standard Values
SharedFields:
- ID: "f1c054a1-c41f-43b5-a597-1fcb4bdb6228"
  Hint: Padding
  Value: 0px 20px 30px
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200313T094812Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d287b574-4f58-4fe6-abb6-960542191785"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200313T094849Z
