---
ID: "9f600000-9469-4011-847b-b144a0bf1255"
Parent: "64fec9d9-d83e-40e2-81c8-bd6e6a654eb3"
Template: "64fec9d9-d83e-40e2-81c8-bd6e6a654eb3"
Path: "/sitecore/templates/Feature/gulfair-app/AirportInfoSection/AirportInfoItem/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/applicationsv2/32x32/history_add.png
- ID: "3c09129a-e8b8-40d8-b82e-0392a2328f2a"
  Hint: WebCheckin
  Value: 
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{1414F315-0767-42DB-986E-C98CA568A2AF}"
- ID: "cde96da4-693c-4270-8fde-fa9ff77e22db"
  Hint: PremiumCheckinService
  Value: "{9338EFBE-D596-4B42-BDDC-721E26CD1C34}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230120T080854Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "38977b5b-fd7b-40a6-af2a-52dd8ce8db0f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shahbaz
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230504T103446Z
