---
ID: "fffed4da-e1bc-4610-98f8-e27c7147628e"
Parent: "b5598e34-0bc7-438f-9f34-4135e2069792"
Template: "b5598e34-0bc7-438f-9f34-4135e2069792"
Path: /sitecore/templates/System/Email/Messages/Base HTML Message/__Standard Values
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{6BCAAECD-3EBD-4633-8902-7DBBDE16DDB6}" mediapath="/Email Campaign/Thumbnails/html-template" src="~/media/6BCAAECD3EBD463389027DBBDE16DDB6.ashx" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1e5221d9-a813-4ee1-bada-33f70028a709"
      Hint: AlternateText
      Value: Your email client does not support HTML mails.
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090616T170200
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e9f52355-7707-4a0e-82bb-ed24cedf0b0d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20140605T123852:635375687329971565"
