---
ID: "c93da5a2-666d-4c7f-bbf6-b47bd3d1a3f4"
Parent: "11d21e68-24c7-45ef-8440-5a68da798553"
Template: "11d21e68-24c7-45ef-8440-5a68da798553"
Path: /sitecore/templates/Project/Rendering Parameters/DestinationStopoverParams/__Standard Values
SharedFields:
- ID: "d9cfe187-85f2-454f-ae6b-44a783e2a18c"
  Hint: CTAColor
  Value: "{F4B4A40B-428A-48B8-907D-F1598EBADC7A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230208T105917Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hassan
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hassan
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7c64fd0a-a140-4554-aaf1-bb2db1e7c056"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\danish
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230413T101924Z
