---
ID: "ac2ec5ee-23fa-49b5-8cf4-bc3c99d5b65d"
Parent: "1d56705b-f96a-4317-8e9a-20d6d590f586"
Template: "1d56705b-f96a-4317-8e9a-20d6d590f586"
Path: /sitecore/templates/Project/Rendering Parameters/EligibilityModuleParams/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230208T105917Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hassan
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hassan
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9dc0e046-5e17-4668-a917-6d99848199eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\hassan
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230412T112456Z
