---
ID: "9a5b6e1f-5e5f-4958-9a3c-391579713fe9"
Parent: "475e9026-333f-432d-a4dc-52e03b75cb6b"
Template: "475e9026-333f-432d-a4dc-52e03b75cb6b"
Path: /sitecore/templates/System/Analytics/Goal/__Standard Values
SharedFields:
- ID: "ac3bc9b6-46a2-4ead-af5e-6bdb532eb832"
  Hint: IsGoal
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20081118T112804
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e8a2df75-26e3-4005-a827-2c5c7138366b"
    - ID: "ac6ba888-4213-43bd-b787-d8da2b6b881f"
      Hint: Name
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160919T155413Z
