---
ID: "e6d06b2a-1b61-4e7e-accc-3fb6a186a3c6"
Parent: "70fd8611-ac5b-4e56-a5c6-dafd8078690b"
Template: "70fd8611-ac5b-4e56-a5c6-dafd8078690b"
Path: "/sitecore/templates/Feature/gulfair-app/AccordianWithPageSlider/AccordianWithPageSliderParent/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{5CCFCCDF-B51D-47CC-8200-ACD509F076D9}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{1414F315-0767-42DB-986E-C98CA568A2AF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230221T120316Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\danish
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\danish
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "346d09a5-41b4-47fd-ba98-cfbf6fd7d2d8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shahbaz
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230504T103458Z
