---
ID: "6bcc5e28-a6e2-477c-bb7c-75d57d5f450a"
Parent: "7ea6a558-d163-4b02-b290-83cdaf8ec29d"
Template: "7ea6a558-d163-4b02-b290-83cdaf8ec29d"
Path: "/sitecore/templates/Feature/gulfair-app/FlightStatusByFlightRoute/FlightStatusByFlightRoute/__Standard Values"
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{1414F315-0767-42DB-986E-C98CA568A2AF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230316T072132Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hassan
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hassan
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aa6c4d68-3b27-469e-bf50-684d209fbd13"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shahbaz
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230504T102724Z
