---
ID: "8e590984-6cd7-45aa-b3d2-64e3c16f7a18"
Parent: "dac9219f-ad8c-4898-9686-2b8518b5ce8e"
Template: "dac9219f-ad8c-4898-9686-2b8518b5ce8e"
Path: /sitecore/templates/Project/Rendering Parameters/FalconFlyerBannerParams/__Standard Values
SharedFields:
- ID: "d9cfe187-85f2-454f-ae6b-44a783e2a18c"
  Hint: CTAColor
  Value: "{F4B4A40B-428A-48B8-907D-F1598EBADC7A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230208T105917Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hassan
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hassan
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "31d318e3-4f9b-484f-9c91-bf7920719d10"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\danish
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230413T101941Z
