---
ID: "9099bfb2-114f-476f-81de-1de0dbb2bc02"
Parent: "2f6277e5-1212-4eee-86ca-599bf40fc4ea"
Template: "2f6277e5-1212-4eee-86ca-599bf40fc4ea"
Path: /sitecore/templates/System/Email/Common Template/Parameter Templates/Preview/__Standard Values
SharedFields:
- ID: "f1c054a1-c41f-43b5-a597-1fcb4bdb6228"
  Hint: Padding
  Value: 30px 20px
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200313T094448Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "67f9e93b-d75b-4b4a-bed6-c582fb1e5cc0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200313T094456Z
