---
ID: "bf609f7c-8e69-40e1-aad3-f860b94d9490"
Parent: "0de95ae4-41ab-4d01-9eb0-67441b7c2450"
Template: "c1f9cdbf-33cb-4722-a0e8-69f42d5451e9"
Path: /sitecore/content/Global Configuration
SharedFields:
- ID: "6fd695e7-7f6d-4ca5-8b49-a829e5950ae9"
  Hint: __Subitems Sorting
  Value: "{44D1A0D2-E17B-4DAA-ADDF-53F2E8F58525}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\GulfAir Content Basic|pe|+item:read|+item:write|pd|+item:read|+item:write|ar|sitecore\GulfAir Test Role Deny|pe|-item:read|-item:write|pd|-item:read|-item:write|ar|sitecore\GulfAir Test Role Allow|pe|+item:read|+item:write|pd|+item:write|+item:read|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230221T080732Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "56c7c137-1b7d-4a60-be75-b3835247a43a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shahbaz
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230509T064322Z
