---
ID: "a06bb324-ae26-4c2a-a86a-4d64d3eee1e4"
Parent: "84f798b8-2746-452d-a1a8-7736aac5bea7"
Template: "84f798b8-2746-452d-a1a8-7736aac5bea7"
Path: /sitecore/templates/System/Experience Explorer/Map Settings/__Standard Values
SharedFields:
- ID: "c2f105d5-4965-4345-9e6a-e407db501759"
  Hint: Map Provider
  Value: "{EBD9A8FB-754E-43EE-BCC6-71D248D88578}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140109T104250Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "356af182-995a-4cbc-b3fe-d2bf6420aec2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170622T123752Z
