---
ID: "40c246ab-4a4e-4a15-82ec-0c6fcc494102"
Parent: "567feb8c-fc3d-49bf-8caf-e62fdb19071e"
Template: "567feb8c-fc3d-49bf-8caf-e62fdb19071e"
Path: /sitecore/templates/Foundation/ComponentBackground/CSSClassFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C2FF4F51-1567-4EC7-9E6E-21046253B30F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230105T063029Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "83ddc4d6-93c9-41fa-a32e-9f5c7192e9ef"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230105T063040Z
