---
ID: "781c667c-d54b-4f23-ad7a-8fc2aa936ae0"
Parent: "ca1fd6e7-3bb6-4d94-8b25-e888507c99fb"
Template: "ca1fd6e7-3bb6-4d94-8b25-e888507c99fb"
Path: /sitecore/templates/System/Email/Global Settings/Hostname Mapping/__Standard Values
SharedFields:
- ID: "4df87612-7e44-4c22-b9c0-68646a30644a"
  Hint: Original
  Value: "http://$name"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170111T123534Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fff0af75-9447-4268-8d5f-fb71fc02b902"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170111T131603Z
