---
ID: "014e8b7e-3ae2-4422-978e-a021a5de2dc5"
Parent: "197c8a18-c17d-46cb-838d-61e88d7d78fa"
Template: "197c8a18-c17d-46cb-838d-61e88d7d78fa"
Path: /sitecore/templates/System/Email/Messages/Inner Content/Content/__Standard Values
SharedFields:
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090617T094603
    - ID: "4abe9631-4175-471f-a9fb-251f1b0e69f6"
      Hint: Body
      Value: "<p>[Enter the body text of your message here]</p>"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "270a8963-8716-486e-ad1c-9151eba42665"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20140611T181323:635381072030015344"
