---
ID: "d06c62b3-b1f6-4583-9a81-44fcb5f0acb5"
Parent: "499bcfb3-6247-4ed2-9404-4b221bcd0edc"
Template: "499bcfb3-6247-4ed2-9404-4b221bcd0edc"
Path: "/sitecore/templates/Feature/gulfair-app/FollowUs/FollowUs/__Standard Values"
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{1414F315-0767-42DB-986E-C98CA568A2AF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230220T112646Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hassan
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hassan
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5e09612d-bf77-4ec2-a2b7-57f6095f5da7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shahbaz
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230504T102713Z
