---
ID: "d0cb779e-5187-4e8b-b089-61c5581de454"
Parent: "f22a1570-ee5e-4607-ace6-8ab2e45a0dd4"
Template: "f22a1570-ee5e-4607-ace6-8ab2e45a0dd4"
Path: /sitecore/templates/System/Content Testing/Workflow/Test Candidate Check Action/__Standard Values
SharedFields:
- ID: "a291a22b-99e2-46bb-a27b-8ec744275396"
  Hint: Type
  Value: Sitecore.ContentTesting.Workflows.TestCandidateCheck, Sitecore.ContentTesting
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140304T122519
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7ad4f8df-efa4-4c57-9dc6-7fdc89f4d7ee"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20140909T014629:635458239895997073Z"
