---
ID: "9c79860e-2be4-4b9d-afa3-d43cc1961c48"
Parent: "5ea0628f-12cc-4840-8463-3dce0ebfbce9"
Template: "5ea0628f-12cc-4840-8463-3dce0ebfbce9"
Path: /sitecore/templates/System/Email/Messages/Inner Content/Subject/__Standard Values
SharedFields:
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090617T094233
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c3bd8108-d38d-46de-816d-bdf5e9407a81"
    - ID: "b393c20b-bf9d-460c-994f-ab37ec6e2c1d"
      Hint: Subject
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20150508T092932:635666741729829107Z"
