---
ID: "be1e9e83-3179-4426-9c8c-3874ce2bdbf5"
Parent: "ffc742af-f5b7-4e08-8b7c-c5cc913fb001"
Template: "ffc742af-f5b7-4e08-8b7c-c5cc913fb001"
Path: /sitecore/templates/Foundation/Number/TimeRange/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "apps/32x32/speed-2.png"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230215T084425Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\fahad
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\fahad
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b1b03140-e713-42dd-93c2-2bfedb27e982"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\fahad
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230215T084523Z
