---
ID: "e04ffda2-d6fb-4226-abf0-5a531134b5d2"
Parent: "8ce42210-cad0-44f8-8ada-d88834a7ed2e"
Template: "8ce42210-cad0-44f8-8ada-d88834a7ed2e"
Path: /sitecore/templates/CMP/Config Root/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{875E0F89-F23B-476B-9BF9-E991A107F693}"
- ID: "21ca0142-2d9e-46ce-99e6-12adeebcd635"
  Hint: Default Language
  Value: "en-US"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190205T124818Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "926f1fd9-d8f2-4828-87eb-c7a451bfa2ce"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190507T082233Z
