---
ID: "2364b1b9-b10a-4dda-a3f4-8087d83f12f1"
Parent: "3505f93a-1bbd-4ea4-bfab-09f44e88a594"
Template: "3505f93a-1bbd-4ea4-bfab-09f44e88a594"
Path: /sitecore/templates/System/Analytics/Marketing Automation/Activity Type/Activity Path/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "229cea16-4ad6-495a-aa42-0e0e05709162"
      Hint: Name
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161222T114154Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e4c627ec-1ce0-43b7-b2ac-3cc921f8f88c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20161222T114157Z
