---
ID: "4ebcffa4-0fab-4830-8fa3-a1ab176d4c68"
Parent: "b19bf3d3-7198-42ca-8cc2-a73b261e3f39"
Template: "b19bf3d3-7198-42ca-8cc2-a73b261e3f39"
Path: /sitecore/templates/Project/Global Modules/Calendar/CalendarFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {4C687CF6-0DFE-43D6-8828-9FA406DBA0FD}
    {AC076D48-02EB-476B-ABCB-0A589CE91156}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230303T072112Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hassan
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hassan
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea8ef16b-c847-4360-b79d-36184ebdeb49"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\hassan
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230411T075515Z
