---
ID: "6f6530cd-5820-400a-bf79-aa1d4381a009"
Parent: "e4100ba5-a3ca-440f-bac2-c0cb325333c7"
Template: "e4100ba5-a3ca-440f-bac2-c0cb325333c7"
Path: /sitecore/templates/System/Content Testing/Historical Test Data/__Standard Values
SharedFields:
- ID: "6fdbf936-0180-4ccd-9893-985df171ab68"
  Hint: Experiences
  Value: 0
- ID: "ab130771-65e6-47d9-aca1-febf2d6b2aed"
  Hint: Test Duration
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150716T094325Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d9116667-7166-4f59-a407-be8b7ac58f06"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20150716T094335Z
