---
ID: "5e6bbd9b-e2e3-48a2-ae98-c92140283338"
Parent: "ac6da6f7-8153-4cc2-857f-386128f027e9"
Template: "ccf252a7-d3e3-401a-95e5-b42bdf2c187a"
Path: /sitecore/content/Global/Global Two Column Section Folder/Corporate Social Responsibility/TwoColumnSectionParent/Aviation and the environment
SharedFields:
- ID: "709d2fac-25a4-45d5-8dc5-23703849e530"
  Hint: Image
  Value: |
    <image width="640" height="474" alt="AviationAndEnvironment.jpg" src="https://dmcc-p-001.sitecorecontenthub.cloud/api/public/content/17cc72b663a94bda8c21b8177463288f?v=78593ced" stylelabs-content-id="39345" stylelabs-content-type="Image" thumbnailsrc="https://dmcc-p-001.sitecorecontenthub.cloud/api/gateway/39345/thumbnail" />
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: "009b7f0e-d357-4c6a-8d21-36c174518aa5"
      Hint: Heading
      Value: الطيران والبيئة
    - ID: "24a462c2-e6ff-407a-b39e-0fb69abec6fc"
      Hint: SubText
      Value: <p>يساهم الطيران 3,5% في الاحتباس الحراري، 2٪ من انبعاثات ثاني أكسيد الكربون حسب 2050. معالجة الصناعة لهذه المشكلة، من المتوقع أن تكون التقنيات الجديدة أكثر كفاءة في استهلاك الوقود بنسبة 50٪. انخفضت الضوضاء بنسبة 75٪، وتحسنت كفاءة الوقود بنسبة 70٪، ليكون الأسطول أكثر كفاءة بنسبة 25٪ بحلول عام 2020. (اتحاد النقل الجوي الدولي)</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230322T082517Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bilalz
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bilalz
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0a444eaa-9260-4776-a533-9b970a4a1b54"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T230221Z
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: "009b7f0e-d357-4c6a-8d21-36c174518aa5"
      Hint: Heading
      Value: Luftfahrt und Umwelt
    - ID: "24a462c2-e6ff-407a-b39e-0fb69abec6fc"
      Hint: SubText
      Value: "<p>Die Luftfahrt tr&auml;gt 3,5% zur globalen Erw&auml;rmung bei, 2% der CO2 -Emissionen bis 2050. Die Industrie befasst sich mit dem Problem, neue Technologien werden voraussichtlich um 50% sparsamer sein. Rauschen reduziert um 75%, die Kraftstoffeffizienz verbesserte sich um 70%, die Flotte um 25%bis 2020 effizienter. (IATA)</p>"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230322T083215Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bilalz
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bilalz
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "02ed2ea0-8bfb-4b3c-92ef-581e05e35e06"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T230221Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "009b7f0e-d357-4c6a-8d21-36c174518aa5"
      Hint: Heading
      Value: Aviation and the Environment
    - ID: "24a462c2-e6ff-407a-b39e-0fb69abec6fc"
      Hint: SubText
      Value: <p>Aviation contributes 3.5% to global warming, 2% of CO2 emissions by 2050. Industry addressing the issue, new technologies expected to be 50% more fuel efficient. Noise reduced by 75%, fuel efficiency improved by 70%, fleet to be 25% more efficient by 2020. (IATA)</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230322T082157Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bilalz
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bilalz
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "07921a93-59b5-4d34-a0f0-6f5b7b562560"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T230221Z
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: "009b7f0e-d357-4c6a-8d21-36c174518aa5"
      Hint: Heading
      Value: L'aviation et l'environnement
    - ID: "24a462c2-e6ff-407a-b39e-0fb69abec6fc"
      Hint: SubText
      Value: <p>L'aviation contribue &agrave; 3,5% au r&eacute;chauffement climatique, 2% des &eacute;missions de CO2 d'ici 2050. L'industrie abordant le probl&egrave;me, les nouvelles technologies devraient &ecirc;tre 50% plus &eacute;conomes en carburant. Le bruit r&eacute;duit de 75%, l'efficacit&eacute; &eacute;nerg&eacute;tique s'est am&eacute;lior&eacute;e de 70%, la flotte est &agrave; 25% plus efficace d'ici 2020. (IATA)</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230322T082908Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bilalz
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bilalz
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c2fd08f8-3634-423b-96cb-c48fbb629438"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T230221Z
- Language: ru
  Versions:
  - Version: 1
    Fields:
    - ID: "009b7f0e-d357-4c6a-8d21-36c174518aa5"
      Hint: Heading
      Value: Авиация и окружающая среда
    - ID: "24a462c2-e6ff-407a-b39e-0fb69abec6fc"
      Hint: SubText
      Value: <p>Aviation приносит 3,5% в глобальное потепление, 2% выбросов CO2 к 2050 году. Промышленность решает эту проблему, ожидается, что новые технологии будут на 50% более эффективными. Шум снизился на 75%, эффективность использования топлива улучшилась на 70%, флот будет на 25%более эффективным к 2020 году. (IATA)</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230322T083812Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bilalz
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bilalz
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f6c482c7-7bed-4020-8143-33fcf0d45bda"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T230221Z
