---
ID: "292ec1f2-f351-4c19-9daa-89de0d51ce65"
Parent: "f07cd31e-82b5-4ff4-9b28-63b368c44185"
Template: "28962446-492a-47fc-864e-d30dfdbe44ad"
Path: /sitecore/content/Dark Site Datasource/Dark Site Configuration
SharedFields:
- ID: "92617a9f-f679-403d-9ce0-4cec0f7cddcc"
  Hint: IsDarkSiteEnabled
  Value: 
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230331T105151Z
    - ID: "34af596e-cc33-4b96-888b-f736dfe6df7f"
      Hint: HomeRouteName
      Value: home
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\danish
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\danish
    - ID: "70c596f6-cffa-44f4-ad15-f8fcbcbe2e87"
      Hint: DarkSitePageURL
      Value: /ar/darksite
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9d94d730-29d8-468f-8a43-5df64f7dc8a1"
    - ID: "943faac5-4aba-4d7c-b43b-69fcfc070014"
      Hint: HomePageURL
      Value: /ar/
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\uiuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230511T055935Z
    - ID: "fb7c44af-2410-4fd5-a98f-29a01f64f05f"
      Hint: DarkRouteName
      Value: darksite
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230517T201229Z
    - ID: "34af596e-cc33-4b96-888b-f736dfe6df7f"
      Hint: HomeRouteName
      Value: home
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{BC6135DC-3933-4BB0-A251-3BD8F315000C}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\qauser
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\qauser
    - ID: "70c596f6-cffa-44f4-ad15-f8fcbcbe2e87"
      Hint: DarkSitePageURL
      Value: /de/darksite
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d547a173-0dfa-45a4-bae9-36748b5c23fe"
    - ID: "943faac5-4aba-4d7c-b43b-69fcfc070014"
      Hint: HomePageURL
      Value: /
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\qauser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230517T201238Z
    - ID: "fb7c44af-2410-4fd5-a98f-29a01f64f05f"
      Hint: DarkRouteName
      Value: darksite
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230331T105151Z
    - ID: "34af596e-cc33-4b96-888b-f736dfe6df7f"
      Hint: HomeRouteName
      Value: home
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\danish
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\danish
    - ID: "70c596f6-cffa-44f4-ad15-f8fcbcbe2e87"
      Hint: DarkSitePageURL
      Value: /darksite
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea632d20-79c0-4bc5-a79c-2d6239eed6bb"
    - ID: "943faac5-4aba-4d7c-b43b-69fcfc070014"
      Hint: HomePageURL
      Value: /
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ghazi
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230604T152046Z
    - ID: "fb7c44af-2410-4fd5-a98f-29a01f64f05f"
      Hint: DarkRouteName
      Value: darksite
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230517T201159Z
    - ID: "34af596e-cc33-4b96-888b-f736dfe6df7f"
      Hint: HomeRouteName
      Value: home
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{BC6135DC-3933-4BB0-A251-3BD8F315000C}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\qauser
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\qauser
    - ID: "70c596f6-cffa-44f4-ad15-f8fcbcbe2e87"
      Hint: DarkSitePageURL
      Value: /fr/darksite
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "596ab566-6bf8-412b-90d6-cd09426598e1"
    - ID: "943faac5-4aba-4d7c-b43b-69fcfc070014"
      Hint: HomePageURL
      Value: /
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\qauser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230517T201226Z
    - ID: "fb7c44af-2410-4fd5-a98f-29a01f64f05f"
      Hint: DarkRouteName
      Value: darksite
- Language: ru
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230510T121708Z
    - ID: "34af596e-cc33-4b96-888b-f736dfe6df7f"
      Hint: HomeRouteName
      Value: home
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{CE5A9C84-B796-475A-B914-1C439E18B43C}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\abyes
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\abyes
    - ID: "70c596f6-cffa-44f4-ad15-f8fcbcbe2e87"
      Hint: DarkSitePageURL
      Value: /ru/darksite
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "59a07a49-20c8-42af-a94b-e43a31fc49d5"
    - ID: "943faac5-4aba-4d7c-b43b-69fcfc070014"
      Hint: HomePageURL
      Value: /
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\abyes
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230510T122200Z
    - ID: "fb7c44af-2410-4fd5-a98f-29a01f64f05f"
      Hint: DarkRouteName
      Value: darksite
