---
ID: "3b16c5b3-598c-4725-b917-1abfa4fb42b6"
Parent: "1efc5a36-4320-478f-8c78-2bfe7506355c"
Template: "1efc5a36-4320-478f-8c78-2bfe7506355c"
Path: /sitecore/templates/Foundation/TextAlignment/TextAlignmentItem/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221223T124715Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "57a6a0ea-175a-4a80-85b1-acf5f0a0f720"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221223T124715Z
