---
ID: "3ec18300-f28d-4be5-b543-0186e062436d"
Parent: "de7a2742-9c9f-4837-a540-20bf6a32b67d"
Template: "05d15730-eae4-491c-b945-137ef6920474"
Path: /sitecore/content/Global/Global Information Tiles Folder/Careers/Information Tiles/Trainees
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
- ID: "d07c6cf5-4e87-4fdc-b467-d8fa8e5e2fb2"
  Hint: Image
  Value: |
    <image width="364" height="240" alt="Entertainment.png" src="https://dmcc-p-001.sitecorecontenthub.cloud/api/public/content/2bc2d182f6ef4884a93766c6727eaf3d?v=3199e949" stylelabs-content-id="39463" stylelabs-content-type="Image" thumbnailsrc="https://dmcc-p-001.sitecorecontenthub.cloud/api/gateway/39463/thumbnail" />
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230124T103517Z
    - ID: "453908c5-24ce-45a6-b436-e0b59dfc5a9d"
      Hint: CTA
      Value: |
        <link id="{61484358-02D6-4F4F-B096-D198EBB30482}" querystring="" linktype="internal" text="View more" anchor="" url="/gulfair-app/home/flying-with-us/on-board/in-flight-entertainment" title="" class="" target="" />
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\danish
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\danish
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "187d1dda-e471-4821-819e-18b7cc240e58"
    - ID: "b888eb28-95c3-4290-9a83-59539996087d"
      Hint: Heading
      Value: Entertainment
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d35a592f-44ad-4533-9a24-eb4c6d7dac5b"
      Hint: SubText
      Value: "Immerse yourself with on demand entertainment with a vast selection of movies, series, audio and games available in a variety of languages and refreshed regularly!"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T225911Z
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230124T103517Z
    - ID: "453908c5-24ce-45a6-b436-e0b59dfc5a9d"
      Hint: CTA
      Value: |
        <link id="{61484358-02D6-4F4F-B096-D198EBB30482}" querystring="" linktype="internal" text="View more" anchor="" url="/gulfair-app/home/flying-with-us/on-board/in-flight-entertainment" title="" class="" target="" />
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\uzair
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\uzair
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "519fafae-bf73-426a-9112-8d8f4e99c3d1"
    - ID: "b888eb28-95c3-4290-9a83-59539996087d"
      Hint: Heading
      Value: Entertainment
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d35a592f-44ad-4533-9a24-eb4c6d7dac5b"
      Hint: SubText
      Value: "Immerse yourself with on demand entertainment with a vast selection of movies, series, audio and games available in a variety of languages and refreshed regularly!"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T225911Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230124T103517Z
    - ID: "453908c5-24ce-45a6-b436-e0b59dfc5a9d"
      Hint: CTA
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "30179f5b-8468-462b-85d6-37f1643c8324"
    - ID: "b888eb28-95c3-4290-9a83-59539996087d"
      Hint: Heading
      Value: Trainees
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d35a592f-44ad-4533-9a24-eb4c6d7dac5b"
      Hint: SubText
      Value: "Trainee Engineers program is a tailored comprehensive programme of intensive on-the-job training for Bahraini nationals who wish to pursue careers in aviation as Aircraft Engineers."
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T225911Z
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230124T103517Z
    - ID: "453908c5-24ce-45a6-b436-e0b59dfc5a9d"
      Hint: CTA
      Value: |
        <link id="{61484358-02D6-4F4F-B096-D198EBB30482}" querystring="" linktype="internal" text="View more" anchor="" url="/gulfair-app/home/flying-with-us/on-board/in-flight-entertainment" title="" class="" target="" />
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\uzair
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\uzair
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c0890363-9243-40fc-bf2c-ec1759fe8a11"
    - ID: "b888eb28-95c3-4290-9a83-59539996087d"
      Hint: Heading
      Value: Entertainment
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d35a592f-44ad-4533-9a24-eb4c6d7dac5b"
      Hint: SubText
      Value: "Immerse yourself with on demand entertainment with a vast selection of movies, series, audio and games available in a variety of languages and refreshed regularly!"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T225911Z
- Language: ru
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230124T103517Z
    - ID: "453908c5-24ce-45a6-b436-e0b59dfc5a9d"
      Hint: CTA
      Value: |
        <link id="{61484358-02D6-4F4F-B096-D198EBB30482}" querystring="" linktype="internal" text="View more" anchor="" url="/gulfair-app/home/flying-with-us/on-board/in-flight-entertainment" title="" class="" target="" />
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\uzair
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\uzair
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a182892f-15b9-4660-88fb-f1f8e4d4c670"
    - ID: "b888eb28-95c3-4290-9a83-59539996087d"
      Hint: Heading
      Value: Entertainment
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d35a592f-44ad-4533-9a24-eb4c6d7dac5b"
      Hint: SubText
      Value: "Immerse yourself with on demand entertainment with a vast selection of movies, series, audio and games available in a variety of languages and refreshed regularly!"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230609T225911Z
