---
ID: "60baa7ff-4f88-41fd-848b-9eeb1d3383de"
Parent: "e7293bbd-8ffb-41a7-af0d-1d92379bcddc"
Template: "e7293bbd-8ffb-41a7-af0d-1d92379bcddc"
Path: /sitecore/templates/System/Email/Sample Newsletter/_FixedSection/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: applications/32x32/form_blue_delete.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160816T055054Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "14aff5e8-9ca2-454b-8109-a07100af199c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200331T123520Z
